name: "Tariq Ali's Blog"
description: "A blog dedicated to showcasing my talents"

# --------------------- #
#    Jekyll Configs     #
# --------------------- #
# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
markdown: kramdown
highlighter: rouge

# ------------------- #
#    Blog Configs     #
# ------------------- #
permalink: /blog/:title.html
paginate_path: "/blog/page:num"
paginate: 5
destination: _site/
gems: ['jekyll-paginate']

# -----------------------#
#  Social Media Configs  #
# -----------------------#
github_username: tra38
linkedin_username: trali
twitter_username: Tariq_Ali38
practical_developer_username: tra

# -----------------------#
#  Collections           #
# -----------------------#
collections:
- accordions
- social_media
- samurai_world_notes